name: "Tag Transmission Plugin OkHttp Test"
description: "Auto test for tag transmission by okhttp"
runs:
  using: composite
  steps:
    - name: entry
      uses: ./.github/actions/common/entry
      with:
        log-dir: ./logs/tag-transmission/okhttp
    - name: package demos
      shell: bash
      run: |
        mvn package -Dokhttpv2.version=${{ matrix.okHttpVersion }} -DskipTests -Pokhttp-test --file \
        sermant-integration-tests/tag-transmission-test/pom.xml
    - name: start okhttp demo
      shell: bash
      run: |
        nohup java -javaagent:sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar=appName=default -jar \
        -Dsermant_log_dir=${{ env.logDir }}/sermant \
        sermant-integration-tests/tag-transmission-test/okhttp-demo/target/okhttp-demo.jar > ${{ env.logDir }}/okhttp.log 2>&1 &
    - name: waiting for services start
      shell: bash
      run: |
        ps -ef | grep java
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:9040/common/httpServer 120
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:9055/okHttp/testOkHttp 120
    - name: test okhttp
      shell: bash
      run: |
        mvn test -Dtag.transmission.integration.test.type=OKHTTP --file \
        sermant-integration-tests/tag-transmission-test/tag-transmission-integration-test/pom.xml
    - name: exit
      if: always()
      uses: ./.github/actions/common/exit
      with:
        processor-keyword: httpserver-common|okhttp
    - name: if failure then upload error log
      uses: actions/upload-artifact@v3
      if: ${{ failure() || cancelled() }}
      with:
        name: (${{ github.job }})-tag-transmission-okhttp-(${{ matrix.okHttpVersion }}-logs
        path: |
          ./*.log
          ./logs/**
        if-no-files-found: warn
        retention-days: 2