  name: "Dubbo Removal Test"
  description: "Automated testing of outlier instance removal plug-in duddo scenario"
  runs:
    using: "composite"
    steps:
      - name: removal-entry
        uses: ./.github/actions/common/entry
        with:
          log-dir: ./logs/dubbo-removal
      - name: package dubbo 2.6.0 tests
        shell: bash
        if: matrix.dubbo-version == '2-6' && matrix.dubbo-versions == '0'
        run: mvn package -Dalibaba.dubbo.version=2.6.${{ matrix.dubbo-versions }} -DskipTests -P260 --file sermant-integration-tests/dubbo-test/pom.xml
      - name: package dubbo 2.6.x tests
        shell: bash
        if: matrix.dubbo-version == '2-6' && matrix.dubbo-versions != '0'
        run: mvn package -Dalibaba.dubbo.version=2.6.${{ matrix.dubbo-versions }} -DskipTests --file sermant-integration-tests/dubbo-test/pom.xml
      - name: package dubbo 2.7.x tests
        shell: bash
        if: matrix.dubbo-version == '2-7'
        run: mvn package -Ddubbo.version=2.7.${{ matrix.dubbo-versions }} -DskipTests --file sermant-integration-tests/dubbo-test/pom.xml
      - name: start provider service
        shell: bash
        run: |
          nohup java -jar sermant-integration-tests/dubbo-test/dubbo-${{ env.projectPath }}-integration-provider/target/dubbo-integration-provider.jar -Dtimeout=2000 -Dserver.port=28021 -Ddubbo.protocol.port=${DUBBO_PROTOCOL_PORT:28821} > ${{ env.logDir }}/removal-provider-28021.log 2>&1 &
      - name: start provider service
        shell: bash
        run: |
          nohup java -jar sermant-integration-tests/dubbo-test/dubbo-${{ env.projectPath }}-integration-provider/target/dubbo-integration-provider.jar -Dtimeout=0 -Dserver.port=28022 -Ddubbo.protocol.port=${DUBBO_PROTOCOL_PORT:28822}  > ${{ env.logDir }}/removal-provider-28022.log 2>&1 &
      - name: start provider service
        shell: bash
        run: |
          nohup java -jar sermant-integration-tests/dubbo-test/dubbo-${{ env.projectPath }}-integration-provider/target/dubbo-integration-provider.jar -Dtimeout=0 -Dserver.port=28023 -Ddubbo.protocol.port=${DUBBO_PROTOCOL_PORT:28823}  > ${{ env.logDir }}/removal-provider-28023.log 2>&1 &
      - name: start consumer service
        shell: bash
        env:
          REMOVAL_CONFIG_EXPIRE_TIMES: 60000
          REMOVAL_CONFIG_EXCEPTIONS: "[com.alibaba.dubbo.remoting.TimeoutException, org.apache.dubbo.remoting.TimeoutException, java.util.concurrent.TimeoutException, java.net.SocketTimeoutException]"
          REMOVAL_CONFIG_ENABLE_REMOVAL: true
          REMOVAL_CONFIG_RECOVERY_TIMES: 30000
          REMOVAL_CONFIG_WINDOWS_TIMES: 1000
          REMOVAL_CONFIG_WINDOWS_NUM: 10
          REMOVAL_CONFIG_RULES: "[{ SCALE_UP_LIMIT: 0.6, MIN_INSTANCE_NUM: 1, ERROR_RATE: 0.6 }]"
          SERVER_PORT: 28020
          DUBBO_PROTOCOL_PORT: 28820
        run: |
          nohup java -javaagent:sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar=appName=dubbo-integration-consumer -jar \
          sermant-integration-tests/dubbo-test/dubbo-${{ env.projectPath }}-integration-consumer/target/dubbo-integration-consumer.jar > ${{ env.logDir }}/removal-consumer-28050.log 2>&1 &
      - name: waiting for services start
        shell: bash
        run: |
          bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:28020/actuator/health 120
          bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:28021/actuator/health 120
          bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:28022/actuator/health 120
          bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:28023/actuator/health 120
      - name: removal test
        shell: bash
        env:
          TEST_TYPE: removal
        run: mvn  test --file sermant-integration-tests/dubbo-test/pom.xml
      - name: exit
        if: always()
        uses: ./.github/actions/common/exit
        with:
          processor-keyword: dubbo
      - name: upload error log
        uses: actions/upload-artifact@v3
        if: ${{ failure() || cancelled() }}
        with:
          name: removal-(${{ matrix.dubbo-version }}-${{ matrix.dubbo-versions }})-logs
          path: |
            ./*.log
            ./logs/**/*.log
          if-no-files-found: warn
          retention-days: 2