name: Backend Integration Test
env:
  sermantVersion: 1.0.0
on:
  push:
  pull_request:
    branches:
      - '*'
    paths:
      - 'sermant-agentcore/**'
      - 'sermant-backend/**'
      - 'sermant-integration-tests/scripts/test_backend*.py'
      - '.github/workflows/backend*.yml'
      - '.github/actions/scenarios/backend/**'
      - '.github/actions/common/backend/action.yml'
      - '.github/actions/common/entry/action.yml'
      - '.github/actions/common/exit/action.yml'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  download-midwares-and-cache:
    name: download midwares and cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache middlewares
        uses: actions/cache@v3
        with:
          path: |
            apache-zookeeper-*/
          key: ${{ runner.os }}-middlewares-${{ github.run_id }}
      - name: download middlewares
        run: |
          export ROOT_PATH=$(pwd)
          bash ./sermant-integration-tests/scripts/tryDownloadMidware.sh zk
          tar -zxf apache-zookeeper-3.6.3-bin.tar.gz
      - name: cache local cse
        uses: actions/cache@v3
        with:
          path: Local-CSE-2.1.3-linux-amd64.zip
          key: ${{ runner.os }}-local-cse
          restore-keys: |
            ${{ runner.os }}-local-cse
      - name: download cse
        run: |
          export ROOT_PATH=$(pwd)
          bash ./sermant-integration-tests/scripts/tryDownloadMidware.sh cse
      - name: cache nacos server
        uses: actions/cache@v3
        with:
          path: nacos-server-2.1.0.tar.gz
          key: ${{ runner.os }}-nacos-server-2.1.0
          restore-keys: |
            ${{ runner.os }}-nacos-server-2.1.0
      - name: download nacos
        run: |
          export ROOT_PATH=$(pwd)
          bash ./sermant-integration-tests/scripts/tryDownloadMidware.sh nacos210
  build-agent-and-cache:
    name: build agent and cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: cache agent
        uses: actions/cache@v3
        with:
          path: sermant-agent-*/
          key: ${{ runner.os }}-agent-${{ github.run_id }}
      - name: package agent
        run: |
          sed -i '/sermant-integration-tests/d' pom.xml
          sed -i '/sermant-injector/d' pom.xml
          mvn package -DskipTests -Ptest --file pom.xml
  test-for-backend:
    name: Test for backend
    runs-on: ubuntu-latest
    needs: [ build-agent-and-cache, download-midwares-and-cache ]
    steps:
      - uses: actions/checkout@v2
      - name: set java version to environment
        run: |
          echo "javaVersion=8" >> $GITHUB_ENV
      - name: start backend common test
        uses: ./.github/actions/common/backend
      - name: start backend use memory test
        uses: ./.github/actions/scenarios/backend/event/memory
      - name: start backend use redis test
        uses: ./.github/actions/scenarios/backend/event/redis
      - name: start config manager test
        uses: ./.github/actions/scenarios/backend/config


