name: Java CI with Maven

on:
  push:
  pull_request:
    branches:
      - master
      - develop

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'testtool'
          checkstyle_config: 'checkstyle.xml'
  build:

    runs-on: windows-latest
    needs:
      - checkstyle_job
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Create License Binary Suffix
        run: |
          mvn license:aggregate-add-third-party
      - name: Build with Maven
        run: |
          mvn -B package -DskipTests --file pom.xml
          mkdir ${{ github.workspace }}/package
          cp ${{ github.workspace }}/sermant-agent-*.tar ${{ github.workspace }}/package
      - name: upload package
        uses: actions/upload-artifact@v1
        with:
          name: sermant
          path: ${{ github.workspace }}/package