name: Pull Request Stats

on: pull_request

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: fo2rist/pull-request-stats@master
        with:
          period: 7
          charts: true
          disable-links: true
          sort-by: 'COMMENTS'
          token: ${{ secrets.GITHUB_TOKEN }}