name: Unit Test

on:
  push:
  pull_request:
    branches:
      - main
      - develop

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # 设置服务器
    steps:
      - uses: actions/checkout@v2 # Action 获取当前分支的源码
      - name: set up JDK 8 # Action 设置 JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: cache maven
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # 使用Maven
      - name: Build and Test
        run: mvn -B test --file pom.xml